### ISSUE TITLE
maximum recursion depth exceeded in 1050 string join

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#231]
*Original report by [jayvdb](https://launchpad.net/~jayvdb) (@jayvdb?) on [Launchpad](https://bugs.launchpad.net/bugs/1507827):*

------------------------------------

Running current pyflakes on astroid results in maximum recursion depth exceeded on a test module.

https://bitbucket.org/logilab/astroid/src/6d4e198bdc7091f36c2c24d911c5ee92b64847c2/astroid/tests/testdata/python2/data/joined_strings.py

```
$ pyflakes  astroid/tests/testdata/python2/data/joined_strings.py
Traceback (most recent call last):
  File "/usr/bin/pyflakes", line 9, in <module>
    load_entry_point('pyflakes==1.0.0', 'console_scripts', 'pyflakes')()
  File "/usr/lib/python2.7/site-packages/pyflakes-1.0.0-py2.7.egg/pyflakes/api.py", line 172, in main
    warnings = checkRecursive(args, reporter)
  File "/usr/lib/python2.7/site-packages/pyflakes-1.0.0-py2.7.egg/pyflakes/api.py", line 129, in checkRecursive
    warnings += checkPath(sourcePath, reporter)
  File "/usr/lib/python2.7/site-packages/pyflakes-1.0.0-py2.7.egg/pyflakes/api.py", line 96, in checkPath
    return check(codestr, filename, reporter)
  File "/usr/lib/python2.7/site-packages/pyflakes-1.0.0-py2.7.egg/pyflakes/api.py", line 57, in check
    w = checker.Checker(tree, filename)
  File "/usr/lib/python2.7/site-packages/pyflakes-1.0.0-py2.7.egg/pyflakes/checker.py", line 294, in __init__
    self.handleChildren(tree)
  File "/usr/lib/python2.7/site-packages/pyflakes-1.0.0-py2.7.egg/pyflakes/checker.py", line 567, in handleChildren
    self.handleNode(node, tree)
  File "/usr/lib/python2.7/site-packages/pyflakes-1.0.0-py2.7.egg/pyflakes/checker.py", line 609, in handleNode
    handler(node)
...
  File "/usr/lib/python2.7/site-packages/pyflakes-1.0.0-py2.7.egg/pyflakes/checker.py", line 609, in handleNode
    handler(node)
  File "/usr/lib/python2.7/site-packages/pyflakes-1.0.0-py2.7.egg/pyflakes/checker.py", line 566, in handleChildren
    for node in iter_child_nodes(tree, omit=omit):
  File "/usr/lib/python2.7/site-packages/pyflakes-1.0.0-py2.7.egg/pyflakes/checker.py", line 80, in iter_child_nodes
    if isinstance(field, ast.AST):
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

Setting sys.setrecursionlimit(2500) fixes the problem

**Comment by Congee** [comment]
can we have a command line flat or config to set the recursion limit? edition the source code is really annoying.

**Comment by AbdealiJK** [comment]
I am also facing this issue in some of my projects.
Is there any interest in resolving the recursive nature ?
I am happy to help and contribute and work on top of jayvdb's previous PR

**Comment by asottile** [comment]
I suspect to actually fix this a full rewrite of pyflakes is necessary.  the current structure depends on recursion to do a tree traversal.  jayvdb's patch _improves_ this but does not eliminate the recursion (so while it may fix some cases, it does not solve all of them)

**Comment by AbdealiJK** [comment]
I see @asottile - thanks for the reply.
Do you think it worthwhile I take a look and see what could potentially be done ?
I assume a full-rewrite is not a great idea ... as it can cause major breakages.

But if there is something to reduce the chance of finding this error - would you be open to getting that merged ? Or are you thinking we should just find a complete fix to the solution ?
