### ISSUE TITLE
Tests fail because imp module is deprecated

### ISSUE THREAD

**Issue by dotlambda** [PyCQA/pyflakes#386]
When running the testsuite, I have 5 tests that fail because of `DeprecationWarning: the imp module is deprecated in favour of importlib`:
```
======================================================================
FAIL: test_errors_io (pyflakes.test.test_api.IntegrationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pyflakes-2.0.0/pyflakes/test/test_api.py", line 735, in test_errors_io
    self.assertEqual(d, ('', error_msg, 1))
AssertionError: Tuples differ: ('', "/nix/store/b888dk7a2fbs1br06h996wyifbsir[297 chars]", 1) != ('', '/build/tmp2oujp6ie/temp: No such file or directory\n', 1)

First differing element 1:
"/nix/store/b888dk7a2fbs1br06h996wyifbsir[293 chars]ry\n"
'/build/tmp2oujp6ie/temp: No such file or directory\n'

- ('',
-  '/nix/store/b888dk7a2fbs1br06h996wyifbsirbxj-python3.7-setuptools-40.5.0/lib/python3.7/site-packages/site.py:26: '
-  'DeprecationWarning: the imp module is deprecated in favour of importlib; see '
-  "the module's documentation for alternative uses\n"
-  '  import imp  # Avoid import loop in Python 3\n'
-  '/build/tmp2oujp6ie/temp: No such file or directory\n',
+ ('', '/build/tmp2oujp6ie/temp: No such file or directory\n', 1)
? ++++                                                        +++

-  1)

======================================================================
FAIL: test_errors_syntax (pyflakes.test.test_api.IntegrationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pyflakes-2.0.0/pyflakes/test/test_api.py", line 749, in test_errors_syntax
    self.assertEqual(d, ('', error_msg, True))
AssertionError: Tuples differ: ('', "/nix/store/b888dk7a2fbs1br06h996wyifbsir[307 chars]", 1) != ('', '/build/tmph9rduv46/temp:1:7: invalid syn[25 chars]True)

First differing element 1:
"/nix/store/b888dk7a2fbs1br06h996wyifbsir[303 chars] ^\n"
'/build/tmph9rduv46/temp:1:7: invalid syn[18 chars] ^\n'

- ('',
-  '/nix/store/b888dk7a2fbs1br06h996wyifbsirbxj-python3.7-setuptools-40.5.0/lib/python3.7/site-packages/site.py:26: '
-  'DeprecationWarning: the imp module is deprecated in favour of importlib; see '
-  "the module's documentation for alternative uses\n"
-  '  import imp  # Avoid import loop in Python 3\n'
-  '/build/tmph9rduv46/temp:1:7: invalid syntax\n'
+ ('', '/build/tmph9rduv46/temp:1:7: invalid syntax\nimport\n      ^\n', True)
? ++++                                               +++++++++++++++++ +++++++

-  'import\n'
-  '      ^\n',
-  1)

======================================================================
FAIL: test_fileWithFlakes (pyflakes.test.test_api.IntegrationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pyflakes-2.0.0/pyflakes/test/test_api.py", line 724, in test_fileWithFlakes
    self.assertEqual(d, ("%s%s" % (expected, os.linesep), '', 1))
AssertionError: Tuples differ: ("/bu[56 chars]\n", "/nix/store/b888dk7a2fbs1br06h996wyifbsir[245 chars]", 1) != ("/bu[56 chars]\n", '', 1)

First differing element 1:
"/nix/store/b888dk7a2fbs1br06h996wyifbsir[241 chars] 3\n"
''

- ("/build/tmpmzpqas06/temp:1: 'contraband' imported but unused\n",
+ ("/build/tmpmzpqas06/temp:1: 'contraband' imported but unused\n", '', 1)
?                                                                  +++++++

-  '/nix/store/b888dk7a2fbs1br06h996wyifbsirbxj-python3.7-setuptools-40.5.0/lib/python3.7/site-packages/site.py:26: '
-  'DeprecationWarning: the imp module is deprecated in favour of importlib; see '
-  "the module's documentation for alternative uses\n"
-  '  import imp  # Avoid import loop in Python 3\n',
-  1)

======================================================================
FAIL: test_goodFile (pyflakes.test.test_api.IntegrationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pyflakes-2.0.0/pyflakes/test/test_api.py", line 712, in test_goodFile
    self.assertEqual(d, ('', '', 0))
AssertionError: Tuples differ: ('', "/nix/store/b888dk7a2fbs1br06h996wyifbsir[245 chars]", 0) != ('', '', 0)

First differing element 1:
"/nix/store/b888dk7a2fbs1br06h996wyifbsir[241 chars] 3\n"
''

+ ('', '', 0)
- ('',
-  '/nix/store/b888dk7a2fbs1br06h996wyifbsirbxj-python3.7-setuptools-40.5.0/lib/python3.7/site-packages/site.py:26: '
-  'DeprecationWarning: the imp module is deprecated in favour of importlib; see '
-  "the module's documentation for alternative uses\n"
-  '  import imp  # Avoid import loop in Python 3\n',
-  0)

======================================================================
FAIL: test_readFromStdin (pyflakes.test.test_api.IntegrationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pyflakes-2.0.0/pyflakes/test/test_api.py", line 757, in test_readFromStdin
    self.assertEqual(d, ("%s%s" % (expected, os.linesep), '', 1))
AssertionError: Tuples differ: ("<st[40 chars]\n", "/nix/store/b888dk7a2fbs1br06h996wyifbsir[245 chars]", 1) != ("<st[40 chars]\n", '', 1)

First differing element 1:
"/nix/store/b888dk7a2fbs1br06h996wyifbsir[241 chars] 3\n"
''

- ("<stdin>:1: 'contraband' imported but unused\n",
+ ("<stdin>:1: 'contraband' imported but unused\n", '', 1)
?                                                  +++++++

-  '/nix/store/b888dk7a2fbs1br06h996wyifbsirbxj-python3.7-setuptools-40.5.0/lib/python3.7/site-packages/site.py:26: '
-  'DeprecationWarning: the imp module is deprecated in favour of importlib; see '
-  "the module's documentation for alternative uses\n"
-  '  import imp  # Avoid import loop in Python 3\n',
-  1)

----------------------------------------------------------------------
```

**Comment by dotlambda** [comment]
See https://github.com/pypa/setuptools/issues/479.

**Comment by asottile** [comment]
these seem to be coming from your `site.py` and not from pyflakes or its test suite.

To confirm, here's an invocation of pyflakes test suite with warnings as errors:
```
$ python3.7 -Werror -m unittest discover pyflakes
......................................s..........s.......s...................s..............................s...s.............s...............................s....................................................s..................s......s...............................................s............ss..s.........s.s.................s...s.............s...............................s.................................................................................s..................s......s...........................................................s.....................sss.....................................s............ss..s.........s.s.
----------------------------------------------------------------------
Ran 643 tests in 0.736s

OK (skipped=34)
```
