### ISSUE TITLE
2.1.0: PYFLAKES_DOCTEST=1 causes stacktrace: AttributeError: 'NoneType' object has no attribute 'parent'

### ISSUE THREAD

**Issue by asottile** [PyCQA/pyflakes#421]
From https://gitlab.com/pycqa/flake8/issues/492

```console
$ pyflakes --version
2.1.0 Python 3.6.7 on Linux
```

```python
import foo as _

def x():
    """doc

    >>> x()
    >>> x()
    """
```

```console
$ PYFLAKES_DOCTEST=1 pyflakes t.py 
Traceback (most recent call last):
  File "/tmp/t/venv/bin/pyflakes", line 10, in <module>
    sys.exit(main())
  File "/tmp/t/venv/lib/python3.6/site-packages/pyflakes/api.py", line 207, in main
    warnings = checkRecursive(args, reporter)
  File "/tmp/t/venv/lib/python3.6/site-packages/pyflakes/api.py", line 156, in checkRecursive
    warnings += checkPath(sourcePath, reporter)
  File "/tmp/t/venv/lib/python3.6/site-packages/pyflakes/api.py", line 99, in checkPath
    return check(codestr, filename, reporter)
  File "/tmp/t/venv/lib/python3.6/site-packages/pyflakes/api.py", line 74, in check
    w = checker.Checker(tree, file_tokens=file_tokens, filename=filename)
  File "/tmp/t/venv/lib/python3.6/site-packages/pyflakes/checker.py", line 665, in __init__
    self.runDeferred(self._deferredFunctions)
  File "/tmp/t/venv/lib/python3.6/site-packages/pyflakes/checker.py", line 702, in runDeferred
    handler()
  File "/tmp/t/venv/lib/python3.6/site-packages/pyflakes/checker.py", line 1410, in <lambda>
    self.deferFunction(lambda: self.handleDoctests(node))
  File "/tmp/t/venv/lib/python3.6/site-packages/pyflakes/checker.py", line 1148, in handleDoctests
    self.addBinding(None, Builtin('_'))
  File "/tmp/t/venv/lib/python3.6/site-packages/pyflakes/checker.py", line 870, in addBinding
    parent_stmt = self.getParent(value.source)
  File "/tmp/t/venv/lib/python3.6/site-packages/pyflakes/checker.py", line 808, in getParent
    node = node.parent
AttributeError: 'NoneType' object has no attribute 'parent'

```

**Comment by asottile** [comment]
fb1f223ac2141772f140be6f1108d02009c1d658 is the first commit that crashes according to bisect CC @MacBox7

**Comment by peterjc** [comment]
Also seeing this in pyflakes  v2.1.1 via ``flake8``, using same basic example:

```python
import foo as _


def x():
    """doc

    >>> x()
    >>> x()
    """
    pass
```

```
$ flake8 --isolated --doctest foo.py ; echo "Return code $?"
"pyflakes" failed during execution due to "'NoneType' object has no attribute 'parent'"
Run flake8 with greater verbosity to see more details
Return code 1
```

Expected behaviour:

```bash
$ flake8 --isolated --doctests foo.py ; echo "Return code $?"
Return code 0
```

Configuration:

```bash
$ flake8 --bug-report
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.7.2",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.1"
    }
  ],
  "version": "3.7.7"
}
```

I thought initially this was triggered by adding some new flake8 plugins, and a clash between them as in https://gitlab.com/pycqa/flake8/issues/536 but this issue seems to be triggered with a plain flake8 installation, and ``--doctest`` is important here.

**Comment by asottile** [comment]
@peterjc, indeed this issue is not resolved and so this is not fixed

**Comment by mgedmin** [comment]
I would like to submit a PR fixing this.  Could anyone help me?

The test to reproduce is easy:

<details>
<summary>patch to add a failing test.</summary>

```diff
diff --git a/pyflakes/test/test_doctests.py b/pyflakes/test/test_doctests.py
index 0825ffe..02ca3fe 100644
--- a/pyflakes/test/test_doctests.py
+++ b/pyflakes/test/test_doctests.py
@@ -191,6 +191,16 @@ class Test(TestCase):
             '''
         """, m.UndefinedName)
 
+    def test_global_underscore(self):
+        self.flakes("""
+        from gettext import ugettext as _
+
+        def doctest_stuff():
+            '''
+                >>> pass
+            '''
+        """, m.UnusedImport)
+
     def test_nested_class(self):
         """Doctest within nested class are processed."""
         self.flakes("""
```

</details>

The fix is, IMHO, in the `Checker.handleDoctests` method that currently does

```python
        self.pushScope(DoctestScope)
        self.addBinding(None, Builtin('_'))
```

I would like to change this to skip the `addBinding()` call when `_` already exists in the outer scope, since that's how doctests work: they define `_` to contain the value of the last expression only when it wasn't already defined.

Does that sound right?
