### ISSUE TITLE
Tuple object has no attribute ctx

### ISSUE THREAD

**Issue by Dreamsorcerer** [PyCQA/pyflakes#537]
With this code:
```
for i in seq_a:
    for j in seq_b:
        print(i, j)
```

Running flake8 gives me this exception:
```
CRITICAL:flake8.checker:Plugin F raised an unexpected exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/checker.py", line 435, in run_check
    return plugin["plugin"](**arguments)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/plugins/pyflakes.py", line 94, in __init__
    file_tokens=file_tokens,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 672, in __init__
    self.handleChildren(tree)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1541, in TUPLE
    if not PY2 and isinstance(node.ctx, ast.Store):
AttributeError: 'Tuple' object has no attribute 'ctx'
"pyflakes" failed during execution due to "'Tuple' object has no attribute 'ctx'"
Run flake8 with greater verbosity to see more details
```

**Comment by asottile** [comment]
what version of python are you using?  I can't reproduce with python3.6.10:

```console
$ python3.6 --version --version
Python 3.6.10 (default, Apr 18 2020, 01:54:07) 
[GCC 9.3.0]
$ python3.6 -m pyflakes t.py
t.py:1:10 undefined name 'seq_a'
t.py:2:14 undefined name 'seq_b'
$ cat t.py
for i in seq_a:
    for j in seq_b:
        print(i, j)
```

there are also no tuples in your example so I suspect your code is different than shown?

**Comment by Dreamsorcerer** [comment]
You're right that the error doesn't seem to appear when run directly. Therefore, I'm not sure if this is a bug here, or in flake8..?

The exception is clearly in pyflakes at that error, which is why I filed a bug here.

With exactly that file, the output I get is:
```
$ flake8 test.py 
CRITICAL:flake8.checker:Plugin F raised an unexpected exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/checker.py", line 435, in run_check
    return plugin["plugin"](**arguments)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/plugins/pyflakes.py", line 94, in __init__
    file_tokens=file_tokens,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 672, in __init__
    self.handleChildren(tree)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1541, in TUPLE
    if not PY2 and isinstance(node.ctx, ast.Store):
AttributeError: 'Tuple' object has no attribute 'ctx'
"pyflakes" failed during execution due to "'Tuple' object has no attribute 'ctx'"
Run flake8 with greater verbosity to see more details
test.py:1:1: D100 Missing docstring in public module
test.py:1:1: SML001 Consider using itertools.product instead of a nested for
test.py:1:1: WPS352 Found multiline loop
test.py:3:9: WPS421 Found wrong function call: print
```

**Comment by Dreamsorcerer** [comment]
Tried doing what it suggested, and ran it with `-vv`, which produces a lot of output, but the closest parts around the exception are:

```
DEBUG:flake8.checker:Running {'name': 'C81', 'parameters': OrderedDict([('tree', True), ('filename', False), ('file_tokens', False)]), 'parameter_names': ['tree', 'filename', 'file_tokens'], 'plugin': <class 'flake8_commas.CommaChecker'>, 'plugin_name': 'flake8_commas'} with {'tree': <_ast.Module object at 0x7f214dccfc88>}
flake8.checker            MainProcess   1470 DEBUG    Running {'name': 'F', 'parameters': OrderedDict([('tree', True), ('file_tokens', True), ('filename', True)]), 'parameter_names': ['tree', 'file_tokens', 'filename'], 'plugin': <class 'flake8.plugins.pyflakes.FlakesChecker'>, 'plugin_name': 'pyflakes'} with {'tree': <_ast.Module object at 0x7f214dccfc88>}
DEBUG:flake8.checker:Running {'name': 'F', 'parameters': OrderedDict([('tree', True), ('file_tokens', True), ('filename', True)]), 'parameter_names': ['tree', 'file_tokens', 'filename'], 'plugin': <class 'flake8.plugins.pyflakes.FlakesChecker'>, 'plugin_name': 'pyflakes'} with {'tree': <_ast.Module object at 0x7f214dccfc88>}
flake8.checker            MainProcess   1471 CRITICAL Plugin F raised an unexpected exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/checker.py", line 435, in run_check
    return plugin["plugin"](**arguments)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/plugins/pyflakes.py", line 94, in __init__
    file_tokens=file_tokens,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 672, in __init__
    self.handleChildren(tree)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1541, in TUPLE
    if not PY2 and isinstance(node.ctx, ast.Store):
AttributeError: 'Tuple' object has no attribute 'ctx'
CRITICAL:flake8.checker:Plugin F raised an unexpected exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/checker.py", line 435, in run_check
    return plugin["plugin"](**arguments)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flake8/plugins/pyflakes.py", line 94, in __init__
    file_tokens=file_tokens,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 672, in __init__
    self.handleChildren(tree)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyflakes/checker.py", line 1541, in TUPLE
    if not PY2 and isinstance(node.ctx, ast.Store):
AttributeError: 'Tuple' object has no attribute 'ctx'
"pyflakes" failed during execution due to "'Tuple' object has no attribute 'ctx'"
Run flake8 with greater verbosity to see more details
flake8.main.application   MainProcess   1475 INFO     Finished running
INFO:flake8.main.application:Finished running
flake8.main.application   MainProcess   1475 INFO     Reporting errors
INFO:flake8.main.application:Reporting errors
```

**Comment by asottile** [comment]
do you maybe have a flake8 plugin that's doing something bad like deleting attributes on objects it doesn't own?

**Comment by asottile** [comment]
can you `flake8 --version`

**Comment by Dreamsorcerer** [comment]
Let's go with, probably:
```
3.7.9 (aaa: 0.9.0, assertive: 1.2.1, flake8-annotations: 2.1.0, flake8-annotations-complexity: 0.0.4, flake8-bandit: 2.1.2, flake8-broken-line: 0.2.0, flake8-bugbear: 20.1.4, flake8-class-attributes-order: 0.1.0, flake8-comprehensions: 3.1.4, flake8-darglint: 0.4.1, flake8-debugger: 3.2.1, flake8-docstrings: 1.5.0, pydocstyle: 5.0.2, flake8-eradicate: 0.3.0, flake8-executable: 2.0.3, flake8-requirements: 1.3.1, flake8-sorted-keys: 0.2.0, flake8-string-format: 0.3.0, flake8-todos: 1.0.0, flake8.datetimez: 19.5.4.0, flake8_coding: 1.3.2, flake8_commas: 2.0.0, flake8_isort: 2.9.1, flake8_quotes: 3.0.0, good-smell: 0.1, import-order: 0.18.1, logging-format: 0.6.0, mccabe: 0.6.1, naming: 0.10.0, pycodestyle: 2.5.0, pyflakes: 2.1.1, radon: 4.1.0, rst-docstrings: 0.0.12, wemake_python_styleguide: 0.13.3) CPython 3.6.8 on Linux
```

**Comment by asottile** [comment]
can you get me that in `pip freeze` form as well, also lol

**Comment by sigmavirus24** [comment]
In that case, we should be able to see which plugin(s) ran before pyflakes if you gave us more of the output prior to the exception.

Also, I have seen lots of tickets where removing the wemake plugin(s) make things work again. I don't know why, but it seems like removing it as a first step often seems to help

**Comment by Dreamsorcerer** [comment]
Funny you say that. I was just trying to remove plugins and isolate the problem. The issue dissapeared when I uninstalled wemake-python-styleguide, but after reinstalling all the plugins, the issue didn't come back (although I have a new error from flake8-aaa which wasn't there before).

**Comment by jamescooke** [comment]
IMO the issue is https://github.com/Tadaboody/good_smell which manipulates the AST provided in `tree` by Flake8. I've been through the list of plugins here and tested them all in a clean venv https://github.com/jamescooke/flake8-aaa/issues/142 < contains my full write up.

**Comment by sigmavirus24** [comment]
@asottile what do you think of Flake8 making copies of the AST it passes into plugins to avoid this in the future? I never bothered for the sake of efficiency but it may make sense?

**Comment by asottile** [comment]
it makes flake8 almost 40% slower (and likely way worse with plugins installed -- this is just for pyflakes in this case) so probably too slow

```console
$ time DEEPCOPY=1 flake8 -j1 pre_commit

real	0m2.974s
user	0m2.949s
sys	0m0.025s
$ time DEEPCOPY=1 flake8 -j1 pre_commit

real	0m2.787s
user	0m2.770s
sys	0m0.016s
$ time DEEPCOPY=1 flake8 -j1 pre_commit

real	0m2.817s
user	0m2.808s
sys	0m0.008s
$ time DEEPCOPY=1 flake8 -j1 pre_commit

real	0m2.836s
user	0m2.815s
sys	0m0.020s
$ time DEEPCOPY=0 flake8 -j1 pre_commit

real	0m2.024s
user	0m2.011s
sys	0m0.013s
$ time DEEPCOPY=0 flake8 -j1 pre_commit

real	0m2.050s
user	0m2.038s
sys	0m0.012s
$ time DEEPCOPY=0 flake8 -j1 pre_commit

real	0m2.064s
user	0m2.051s
sys	0m0.012s
$ python3 -c 'print((2.787 - 2.024) / 2.024 * 100)'
37.697628458498016
```

**Comment by sigmavirus24** [comment]
If only we could make the AST immutable when lending it to plugins.

**Comment by asottile** [comment]
> If only we could make the AST immutable when lending it to plugins.

[even pyflakes makes mutations to it >.<](https://github.com/PyCQA/pyflakes/blob/da385d5d65c6f515ae0ca88338b0a2e7a5c19c9c/pyflakes/checker.py#L1342-L1343)

**Comment by sigmavirus24** [comment]
Copy on mutate then =P

**Comment by jamescooke** [comment]
> If only we could make the AST immutable when lending it to plugins.

I thought this too - but then I realised that Flake8-AAA is actually mutating the AST too :hurtrealbad: ... Calling [asttokens](https://github.com/gristlabs/asttokens) adds `first_token` and `last_token` attributes to the `ast.AST` nodes.

**Comment by sigmavirus24** [comment]
I think really adding to the AST is probably fine but mutating documented/well-known attributes or deleting nodes altogether is probably super bad

**Comment by asottile** [comment]
could probably maybe do some hack with setattr and looking at `_fields`, I'll see what I can come up with and how terrible it is 😆

**Comment by sigmavirus24** [comment]
@asottile I was just thinking out loud at this point, not trying to heap more work on your plate :disappointed:

**Comment by asottile** [comment]
<3 it's all good -- this is an interesting problem that comes up a surprisingly often

**Comment by jamescooke** [comment]
Hi @asottile - could you share some pointers to where this has come up before? I've only seen this one instance.

With this case it looks like good_smell is using instances of `ast.NodeTransformer`. For example here: https://github.com/Tadaboody/good_smell/blob/038a52555d0c5373d6661599f710df0a6548f130/good_smell/smells/nested_for.py#L41-L56

**Comment by asottile** [comment]
last time it was `bandit` vs `pyflakes`, I can find links if you'd like when I'm at a computer

**Comment by jamescooke** [comment]
Does this look like the right thing? https://github.com/PyCQA/bandit/issues/487

**Comment by asottile** [comment]
yes
