### ISSUE TITLE
Whalrus operator gives AttributeError

### ISSUE THREAD

**Issue by 8Kuula** [PyCQA/pyflakes#564]
Code
```
if (x := 'test') == 'test':
    print(f'x is a {x}')
```

pyflakes
```
$ pyflakes3 test.py
Traceback (most recent call last):
  File "/usr/bin/pyflakes3", line 11, in <module>
    load_entry_point('pyflakes==2.1.1', 'console_scripts', 'pyflakes')()
  File "/usr/lib/python3/dist-packages/pyflakes/api.py", line 207, in main
    warnings = checkRecursive(args, reporter)
  File "/usr/lib/python3/dist-packages/pyflakes/api.py", line 156, in checkRecursive
    warnings += checkPath(sourcePath, reporter)
  File "/usr/lib/python3/dist-packages/pyflakes/api.py", line 99, in checkPath
    return check(codestr, filename, reporter)
  File "/usr/lib/python3/dist-packages/pyflakes/api.py", line 74, in check
    w = checker.Checker(tree, file_tokens=file_tokens, filename=filename)
  File "/usr/lib/python3/dist-packages/pyflakes/checker.py", line 672, in __init__
    self.handleChildren(tree)
  File "/usr/lib/python3/dist-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/usr/lib/python3/dist-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/usr/lib/python3/dist-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/usr/lib/python3/dist-packages/pyflakes/checker.py", line 1120, in handleNode
    handler(node)
  File "/usr/lib/python3/dist-packages/pyflakes/checker.py", line 1698, in COMPARE
    self.handleChildren(node)
  File "/usr/lib/python3/dist-packages/pyflakes/checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "/usr/lib/python3/dist-packages/pyflakes/checker.py", line 1119, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "/usr/lib/python3/dist-packages/pyflakes/checker.py", line 909, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'Checker' object has no attribute 'NAMEDEXPR'
```
version: 2.1.1 Python 3.8.2 on Linux

Code executed
```
$ python3 test.py 
x is a test
```

**Comment by sigmavirus24** [comment]
This was fixed in 2.2.0 as tracked by #520. Please upgrade
