### ISSUE TITLE
F821 when referencing class variable

### ISSUE THREAD

**Issue by dmtucker** [PyCQA/pyflakes#573]
2.2.0 Python 3.8.2 on Linux
``` python
from typing import Dict


class Foo:

    _bar_type = Dict[str, int]

    def __init__(self, bar: _bar_type):
        self.bar = bar

    @classmethod
    def baz(cls) -> 'Foo':
        bar: _bar_type = {}
        return cls(bar)
```
```
foo.py:13:14 undefined name '_bar_type'
```

**Comment by dmtucker** [comment]
This isn't valid... `_bar_type` _really_ isn't defined:
``` python
from typing import Dict


class Foo:

    _bar_type = Dict[str, int]

    @classmethod
    def baz(cls) -> 'Foo':
        _bar_type

Foo.baz()
```
```
Traceback (most recent call last):
  File "foo.py", line 13, in <module>
    Foo.baz()
  File "foo.py", line 11, in baz
    _bar_type
NameError: name '_bar_type' is not defined
```

**Comment by asottile** [comment]
this error is correct:

```console
$ mypy t.py
t.py:13: error: Name '_bar_type' is not defined
Found 1 error in 1 file (checked 1 source file)
```

the proper annotation for line 13 is:

```python
bar: Foo._bar_type = {}
```

**Comment by dmtucker** [comment]
@asottile Thanks! FWIW, I had actually tried `cls._bar_type`, which `pyflakes` seems ok with (but not `mypy`).

**Comment by asottile** [comment]
yeah pyflakes tries to enforce the scoping rules, but can't know whether something is a valid type or not (`cls` is in scope at that point so it makes sense that pyflakes would allow it)
