### ISSUE TITLE
test_invalidEscape fails with PyPy3

### ISSUE THREAD

**Issue by sbraz** [PyCQA/pyflakes#584]
Hi,
I see that https://github.com/PyCQA/pyflakes/pull/354 re-enabled this test for PyPy, however it fails for me with PyPy 7.3.2 (both the 3.6 and 3.7 variants).
```
FAIL: test_invalidEscape (test.test_api.CheckTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyflakes/pyflakes/test/test_api.py", line 600, in test_invalidEscape
    sourcePath, [decoding_error])
  File "/tmp/pyflakes/pyflakes/test/test_api.py", line 380, in assertHasErrors
    (count, err.getvalue()), (len(errorList), ''.join(errorList)))
AssertionError: Tuples differ: (1, "[14 chars]3l:1:5: (unicode error) 'unicodeescape' codec [79 chars]^\n") != (1, "[14 chars]3l:1:6: (unicode error) 'unicodeescape' codec [80 chars]^\n")

First differing element 1:
"/tmp/tmp_4l9f33l:1:5: (unicode error) 'unicodeescape' codec [78 chars] ^\n"
"/tmp/tmp_4l9f33l:1:6: (unicode error) 'unicodeescape' codec [79 chars] ^\n"

  (1,
-  "/tmp/tmp_4l9f33l:1:5: (unicode error) 'unicodeescape' codec can't decode "
?                      ^

+  "/tmp/tmp_4l9f33l:1:6: (unicode error) 'unicodeescape' codec can't decode "
?                      ^

   'bytes in position 0-1: truncated \\xXX escape\n'
   "foo = '\\xyz'\n"
-  '    ^\n')
+  '     ^\n')
?   +


----------------------------------------------------------------------
```

**Comment by asottile** [comment]
yeah these tests are particularly sensitive to python versions unfortunately

would you like to attempt a patch which upgrades pypy and fixes the test?  the functionality is actually ok just the offsets are slightly different

**Comment by sbraz** [comment]
I initially wanted to file a PR but I saw the multiline string comparison and I thought to myself "this is going to be a bit tricky, I'm just going to be lazy and report it" :smile: 

I'll look into it a little, maybe it's not that complex.
