### ISSUE TITLE
Compatibility with Python 3.10

### ISSUE THREAD

**Issue by frenzymadness** [PyCQA/pyflakes#613]
Hello.

It seems that there is a minor incompatibility with Python 3.10 (aplha 5, currently):

```
======================================================================
FAIL: test_eofSyntaxError (test.test_api.CheckTests)
The error reported for source files which end prematurely causing a
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbalhar/Software/pyflakes/pyflakes/test/test_api.py", line 483, in test_eofSyntaxError
    self.assertHasErrors(
  File "/home/lbalhar/Software/pyflakes/pyflakes/test/test_api.py", line 379, in assertHasErrors
    self.assertEqual(
AssertionError: Tuples differ: (1, "/tmp/tmpm458dna8:1:8: '(' was never closed\ndef foo(\n       ^\n") != (1, '/tmp/tmpm458dna8:1:9: unexpected EOF while parsing\ndef foo(\n        ^\n')

First differing element 1:
"/tmp/tmpm458dna8:1:8: '(' was never closed\ndef foo(\n       ^\n"
'/tmp/tmpm458dna8:1:9: unexpected EOF while parsing\ndef foo(\n        ^\n'

- (1, "/tmp/tmpm458dna8:1:8: '(' was never closed\ndef foo(\n       ^\n")
+ (1, '/tmp/tmpm458dna8:1:9: unexpected EOF while parsing\ndef foo(\n        ^\n')

======================================================================
FAIL: test_multilineSyntaxError (test.test_api.CheckTests)
Source which includes a syntax error which results in the raised
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbalhar/Software/pyflakes/pyflakes/test/test_api.py", line 441, in test_multilineSyntaxError
    evaluate(source)
  File "<string>", line 8
    '''quux'''
           ^
SyntaxError: unterminated triple-quoted string literal (detected at line 8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lbalhar/Software/pyflakes/pyflakes/test/test_api.py", line 445, in test_multilineSyntaxError
    self.assertTrue(e.text.count('\n') > 1)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 747 tests in 2.888s

FAILED (failures=2, skipped=37)
```

**Comment by asottile** [comment]
feel free to send a patch though we usually wait until beta freeze to adjust to these sorts of things (the syntax error changes often go through a few rounds of adjustment before python finalizes)

**Comment by hrnciar** [comment]
Hello @asottile, 1st beta is out and this error is still present. Could you please reopen this issue? Thank you.

**Comment by musicinmybrain** [comment]
This seems to have been fixed in https://github.com/PyCQA/pyflakes/pull/635.

**Comment by mcepl** [comment]
Perhaps somebody can use [this patch](https://github.com/user-attachments/files/19559579/modify-failing-tests.patch.txt) making the test suite pass from Python 3.6 to 3.11.

**Comment by sigmavirus24** [comment]
3.6 to 3.8 are end of life and unsupported.

**Comment by mcepl** [comment]
Of course, I know that, but some of us work in companies where we maintain old stuff, and I would think somebody might be interested.
