### ISSUE TITLE
AttributeError in parsing Python 3.10 parsing pattern matching with keyword arguments

### ISSUE THREAD

**Issue by tirkarthi** [PyCQA/pyflakes#634]
This doesn't happen with positional only argument matches but keyword argument pattern matching as below throws error.

```python 3.10
import dataclasses


@dataclasses.dataclass()
class C(object):
    a: int
    b: int


c = C(1, 2)
match c:
    case C(a=a, b=b):
        found = True
```

Traceback

```
pyflakes /tmp/test_pattern_matching.py
Traceback (most recent call last):
  File "/root/checked_repos/attrs/.env/bin/pyflakes", line 8, in <module>
    sys.exit(main())
  File "/root/checked_repos/attrs/.env/lib/python3.10/site-packages/pyflakes/api.py", line 210, in main
    warnings = checkRecursive(args, reporter)
  File "/root/checked_repos/attrs/.env/lib/python3.10/site-packages/pyflakes/api.py", line 155, in checkRecursive
    warnings += checkPath(sourcePath, reporter)
  File "/root/checked_repos/attrs/.env/lib/python3.10/site-packages/pyflakes/api.py", line 99, in checkPath
    return check(codestr, filename, reporter)
  File "/root/checked_repos/attrs/.env/lib/python3.10/site-packages/pyflakes/api.py", line 74, in check
    w = checker.Checker(tree, file_tokens=file_tokens, filename=filename)
  File "/root/checked_repos/attrs/.env/lib/python3.10/site-packages/pyflakes/checker.py", line 904, in __init__
    self.handleChildren(tree)
  File "/root/checked_repos/attrs/.env/lib/python3.10/site-packages/pyflakes/checker.py", line 1359, in handleChildren
    self.handleNode(node, tree)
  File "/root/checked_repos/attrs/.env/lib/python3.10/site-packages/pyflakes/checker.py", line 1406, in handleNode
    handler(node)
  File "/root/checked_repos/attrs/.env/lib/python3.10/site-packages/pyflakes/checker.py", line 1166, in _unknown_handler
    self.handleChildren(node)
  File "/root/checked_repos/attrs/.env/lib/python3.10/site-packages/pyflakes/checker.py", line 1359, in handleChildren
    self.handleNode(node, tree)
  File "/root/checked_repos/attrs/.env/lib/python3.10/site-packages/pyflakes/checker.py", line 1406, in handleNode
    handler(node)
  File "/root/checked_repos/attrs/.env/lib/python3.10/site-packages/pyflakes/checker.py", line 1166, in _unknown_handler
    self.handleChildren(node)
  File "/root/checked_repos/attrs/.env/lib/python3.10/site-packages/pyflakes/checker.py", line 1359, in handleChildren
    self.handleNode(node, tree)
  File "/root/checked_repos/attrs/.env/lib/python3.10/site-packages/pyflakes/checker.py", line 1406, in handleNode
    handler(node)
  File "/root/checked_repos/attrs/.env/lib/python3.10/site-packages/pyflakes/checker.py", line 1166, in _unknown_handler
    self.handleChildren(node)
  File "/root/checked_repos/attrs/.env/lib/python3.10/site-packages/pyflakes/checker.py", line 1359, in handleChildren
    self.handleNode(node, tree)
  File "/root/checked_repos/attrs/.env/lib/python3.10/site-packages/pyflakes/checker.py", line 1402, in handleNode
    node._pyflakes_depth = self.nodeDepth
AttributeError: 'str' object has no attribute '_pyflakes_depth'
```

**Comment by asottile** [comment]
match support is not at all implemented yet -- if you want to move that along please review #630

**Comment by tirkarthi** [comment]
Sorry, search failed me. Please feel free to close it or as #630 is implemented. Thanks.

**Comment by asottile** [comment]
via #630
