### ISSUE TITLE
Multiple test failures with PyPy3.9 7.3.9

### ISSUE THREAD

**Issue by mgorny** [PyCQA/pyflakes#697]
It seems that there are some column number mismatches with pypy3.9:

```pytb
pypy3 run-test: commands[1] | python -m unittest discover pyflakes
......F....FFF........................s..........................s.......s....................s..............................s...s.............s...............................s...............................................s....s..................s......s..............................................s.............ss..s.........s.s.................s...s.............s...............................s....................................................................................................sssssss.............s....s..................s......s.................s............................................s.....................sss.........................................................................................s.............ss..s.........s.s.
======================================================================
FAIL: test_invalidEscape (test.test_api.CheckTests)
The invalid escape syntax raises ValueError in Python 2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyflakes/pyflakes/test/test_api.py", line 616, in test_invalidEscape
    self.assertHasErrors(
  File "/tmp/pyflakes/pyflakes/test/test_api.py", line 379, in assertHasErrors
    self.assertEqual(
AssertionError: Tuples differ: (1, "[14 chars]0n:1:6: (unicode error) 'unicodeescape' codec [80 chars]^\n") != (1, "[14 chars]0n:1:5: (unicode error) 'unicodeescape' codec [79 chars]^\n")

First differing element 1:
"/tmp/tmpxaya6p0n:1:6: (unicode error) 'unicodeescape' codec [79 chars] ^\n"
"/tmp/tmpxaya6p0n:1:5: (unicode error) 'unicodeescape' codec [78 chars] ^\n"

  (1,
-  "/tmp/tmpxaya6p0n:1:6: (unicode error) 'unicodeescape' codec can't decode "
?                      ^

+  "/tmp/tmpxaya6p0n:1:5: (unicode error) 'unicodeescape' codec can't decode "
?                      ^

   'bytes in position 0-1: truncated \\xXX escape\n'
   "foo = '\\xyz'\n"
-  '     ^\n')
?   -

+  '    ^\n')

======================================================================
FAIL: test_multilineSyntaxError (test.test_api.CheckTests)
Source which includes a syntax error which results in the raised
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyflakes/pyflakes/test/test_api.py", line 463, in test_multilineSyntaxError
    self.assertHasErrors(
  File "/tmp/pyflakes/pyflakes/test/test_api.py", line 379, in assertHasErrors
    self.assertEqual(
AssertionError: Tuples differ: (1, "[14 chars]jx:8:11: end of file (EOF) while scanning trip[52 chars]^\n") != (1, "[14 chars]jx:8:8: end of file (EOF) while scanning tripl[48 chars]^\n")

First differing element 1:
"/tmp/tmp1ww86xjx:8:11: end of file (EOF) while scanning trip[51 chars] ^\n"
"/tmp/tmp1ww86xjx:8:8: end of file (EOF) while scanning tripl[47 chars] ^\n"

  (1,
-  '/tmp/tmp1ww86xjx:8:11: end of file (EOF) while scanning triple-quoted string '
?                      ^^

+  '/tmp/tmp1ww86xjx:8:8: end of file (EOF) while scanning triple-quoted string '
?                      ^

   'literal\n'
   "    '''quux'''\n"
-  '          ^\n')
?   ---

+  '       ^\n')

======================================================================
FAIL: test_nonDefaultFollowsDefaultSyntaxError (test.test_api.CheckTests)
Source which has a non-default argument following a default argument
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyflakes/pyflakes/test/test_api.py", line 541, in test_nonDefaultFollowsDefaultSyntaxError
    self.assertHasErrors(
  File "/tmp/pyflakes/pyflakes/test/test_api.py", line 379, in assertHasErrors
    self.assertEqual(
AssertionError: Tuples differ: (1, '[14 chars]r9:1:17: non-default argument follows default [50 chars]^\n') != (1, '[14 chars]r9:1:7: non-default argument follows default a[39 chars]^\n')

First differing element 1:
'/tmp/tmpcrltdfr9:1:17: non-default argument follows default [49 chars] ^\n'
'/tmp/tmpcrltdfr9:1:7: non-default argument follows default a[38 chars] ^\n'

  (1,
-  '/tmp/tmpcrltdfr9:1:17: non-default argument follows default argument\n'
?                      -

+  '/tmp/tmpcrltdfr9:1:7: non-default argument follows default argument\n'
   'def foo(bar=baz, bax):\n'
-  '                ^\n')
+  '      ^\n')

======================================================================
FAIL: test_nonKeywordAfterKeywordSyntaxError (test.test_api.CheckTests)
Source which has a non-keyword argument after a keyword argument should
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyflakes/pyflakes/test/test_api.py", line 577, in test_nonKeywordAfterKeywordSyntaxError
    self.assertHasErrors(
  File "/tmp/pyflakes/pyflakes/test/test_api.py", line 379, in assertHasErrors
    self.assertEqual(
AssertionError: Tuples differ: (1, '[15 chars]b:1:16: positional argument follows keyword ar[42 chars]^\n') != (1, '[15 chars]b:1:12: positional argument follows keyword ar[38 chars]^\n')

First differing element 1:
'/tmp/tmp2snn7gpb:1:16: positional argument follows keyword ar[41 chars] ^\n'
'/tmp/tmp2snn7gpb:1:12: positional argument follows keyword ar[37 chars] ^\n'

  (1,
-  '/tmp/tmp2snn7gpb:1:16: positional argument follows keyword argument\n'
?                       ^

+  '/tmp/tmp2snn7gpb:1:12: positional argument follows keyword argument\n'
?                       ^

   'foo(bar=baz, bax)\n'
-  '               ^\n')
?   ----

+  '           ^\n')

```

**Comment by asottile** [comment]
should be fixed now!
