### ISSUE TITLE
AttributeError: module 'pyflakes.messages' has no attribute 'RedefinedInListComp'

### ISSUE THREAD

**Issue by jpetidis** [PyCQA/pyflakes#721]
Occuring on ubuntu latest (Github actions)  - pyflakes==2.5.0.

When running pyflakes==2.4.0 - issue is resolved.

--- Performing pylama linting ---
pylama .
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.13/x64/bin/pylama", line 5, in <module>
    from pylama.main import shell
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pylama/main.py", line [11](,<REDACTED>), in <module>
    from pylama.check_async import check_async
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pylama/check_async.py", line 8, in <module>
    from pylama.config import Namespace
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pylama/config.py", line 13, in <module>
    from pylama.lint import LINTERS
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/pylama/lint/__init__.py", line 56, in <module>
    import_module(f"{__name__}.{pname}")
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/importlib/__init__.py", line [12](https://github.com/<REDACTED>?check_suite_focus=true#step:6:13)7, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/hostedtoolcache/Python/3.9.[13](https://github.com/<REDACTED>?check_suite_focus=true#step:6:14)/x64/lib/python3.9/site-packages/pylama/lint/pylama_pyflakes.py", line 12, in <module>
    m.RedefinedInListComp.message: "W0621",
AttributeError: module 'pyflakes.messages' has no attribute 'RedefinedInListComp'

**Comment by iflare3g** [comment]
Thanks for reporting it! I'm having the same issue by using pylama hook in pre-commit and it works only if I bumps pyflakes to 2.4.0

**Comment by kalanatd** [comment]
I am having the same issue, I can not use [pylama](https://github.com/klen/pylama) and it throws the aforementioned error.

**Comment by iflare3g** [comment]
> I am having the same issue, I can not use [pylama](https://github.com/klen/pylama) and it throws the aforementioned error.

in the meanwhile you make it working by bumping pyflakes to 2.4.0 and pylama will work

**Comment by asottile** [comment]
this is not a pyflakes issue -- pylama is accessing errors that don't exist any more -- you should report it there

**Comment by iflare3g** [comment]
Thanks so much @asottile !

**Comment by djbrown** [comment]
corresponding issue over at pylama would be https://github.com/klen/pylama/issues/224
