### ISSUE TITLE
v2.5.0: AttributeError: module 'pyflakes.messages' has no attribute 'RedefinedInListComp'

### ISSUE THREAD

**Issue by mbelang** [PyCQA/pyflakes#722]
Since the upgrade to pyflake 2.5.0, running pylama brakes with the following stack trace

```
Traceback (most recent call last):
  File "/home/circleci/project/.venv/bin/pylama", line 5, in <module>
    from pylama.main import shell
  File "/home/circleci/project/.venv/lib/python3.10/site-packages/pylama/main.py", line 11, in <module>
    from pylama.check_async import check_async
  File "/home/circleci/project/.venv/lib/python3.10/site-packages/pylama/check_async.py", line 8, in <module>
    from pylama.config import Namespace
  File "/home/circleci/project/.venv/lib/python3.10/site-packages/pylama/config.py", line 13, in <module>
    from pylama.lint import LINTERS
  File "/home/circleci/project/.venv/lib/python3.10/site-packages/pylama/lint/__init__.py", line 56, in <module>
    import_module(f"{__name__}.{pname}")
  File "/home/circleci/.pyenv/versions/3.10.5/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/circleci/project/.venv/lib/python3.10/site-packages/pylama/lint/pylama_pyflakes.py", line 12, in <module>
    m.RedefinedInListComp.message: "W0621",
AttributeError: module 'pyflakes.messages' has no attribute 'RedefinedInListComp'
```

pylama config

```
[pylama]
paths = my_project tests
linters = pycodestyle,pyflakes,pydocstyle
# derived from google convention https://www.pydocstyle.org/en/stable/error_codes.html#default-conventions
ignore = D100,D101,D102,D103,D104,D105,D106,D107,D203,D204,D205,D212,D213,D215,D300,D400,D401,D404,D406,D407,D408,D409,D413,D415

[pylama:pycodestyle]
max_line_length = 89

[pylama:radon]
no_assert = true
```

**Comment by asottile** [comment]
search the issue tracker, #721  -- literally the issue right before you
