### ISSUE TITLE
Test regressions with PyPy3.10

### ISSUE THREAD

**Issue by mgorny** [PyCQA/pyflakes#779]
The test suite fails with PyPy3.10 7.3.12:

```pytb
$ tox -e pypy310
pypy310: install_deps> python -I -m pip install flake8==6.0.0
.pkg: _optional_hooks> python /usr/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_sdist> python /usr/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_wheel> python /usr/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: prepare_metadata_for_build_wheel> python /usr/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: build_sdist> python /usr/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
pypy310: install_package> python -I -m pip install --force-reinstall --no-deps /tmp/pyflakes/.tox/.tmp/package/3/pyflakes-3.1.0.tar.gz
pypy310: commands[0]> python --version --version
Python 3.10.12 (af44d0b8114cb82c40a07bb9ee9c1ca8a1b3688c, Jul 21 2023, 09:40:48)
[PyPy 7.3.12 with GCC 12.3.1 20230526]
pypy310: commands[1]> python -m unittest discover pyflakes
....F....F.F..................................................................s.................................s...............................................................................................s....................................................................................ss..s..........s....................s.........................................................................................................................................................................s.................................................................................s........s......................................................sssss..........s..................................................ss..s..........s.
======================================================================
FAIL: test_eofSyntaxError (test.test_api.CheckTests)
The error reported for source files which end prematurely causing a
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyflakes/pyflakes/test/test_api.py", line 450, in test_eofSyntaxError
    self.assertHasErrors(sourcePath, [expected])
  File "/tmp/pyflakes/pyflakes/test/test_api.py", line 338, in assertHasErrors
    self.assertEqual(
AssertionError: Tuples differ: (1, "/tmp/tmp834rbkod:1:8: '(' was never closed\ndef foo(\n       ^\n") != (1, '/tmp/tmp834rbkod:1:8: parenthesis is never closed\ndef foo(\n       ^\n')

First differing element 1:
"/tmp/tmp834rbkod:1:8: '(' was never closed\ndef foo(\n       ^\n"
'/tmp/tmp834rbkod:1:8: parenthesis is never closed\ndef foo(\n       ^\n'

- (1, "/tmp/tmp834rbkod:1:8: '(' was never closed\ndef foo(\n       ^\n")
?     ^                      ^^^^^                                     ^

+ (1, '/tmp/tmp834rbkod:1:8: parenthesis is never closed\ndef foo(\n       ^\n')
?     ^                      ^ ++++++ +++++                                   ^


======================================================================
FAIL: test_misencodedFileUTF8 (test.test_api.CheckTests)
If a source file contains bytes which cannot be decoded, this is
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyflakes/pyflakes/test/test_api.py", line 614, in test_misencodedFileUTF8
    self.assertHasErrors(
  File "/tmp/pyflakes/pyflakes/test/test_api.py", line 338, in assertHasErrors
    self.assertEqual(
AssertionError: Tuples differ: (1, "[14 chars]nf:1: 'ascii' codec can't decode byte 0xe2 in [54 chars]i\n") != (1, "[14 chars]nf:1:1: 'ascii' codec can't decode byte 0xe2 i[39 chars])\n")

First differing element 1:
"/tmp/tmpzxw0qinf:1: 'ascii' codec can't decode byte 0xe2 in [53 chars]ii\n"
"/tmp/tmpzxw0qinf:1:1: 'ascii' codec can't decode byte 0xe2 i[38 chars]8)\n"

  (1,
-  "/tmp/tmpzxw0qinf:1: 'ascii' codec can't decode byte 0xe2 in position 21: "
+  "/tmp/tmpzxw0qinf:1:1: 'ascii' codec can't decode byte 0xe2 in position 21: "
?                      ++

-  'ordinal not in range(128)\n'
+  'ordinal not in range(128)\n')
?                               +

-  '# coding: ascii\n')

======================================================================
FAIL: test_multilineSyntaxError (test.test_api.CheckTests)
Source which includes a syntax error which results in the raised
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pyflakes/pyflakes/test/test_api.py", line 419, in test_multilineSyntaxError
    self.assertHasErrors(
  File "/tmp/pyflakes/pyflakes/test/test_api.py", line 338, in assertHasErrors
    self.assertEqual(
AssertionError: Tuples differ: (1, "[18 chars]:12: unterminated triple-quoted string literal[50 chars]^\n") != (1, "[18 chars]:12: end of file (EOF) while scanning triple-q[49 chars]^\n")

First differing element 1:
"/tmp[14 chars]:12: unterminated triple-quoted string literal[49 chars] ^\n"
"/tmp[14 chars]:12: end of file (EOF) while scanning triple-q[48 chars] ^\n"

  (1,
-  '/tmp/tmp0cufqo66:8:12: unterminated triple-quoted string literal (detected '
-  'at line 8)\n'
+  '/tmp/tmp0cufqo66:8:12: end of file (EOF) while scanning triple-quoted string '
+  'literal\n'
   "    '''quux'''\n"
   '           ^\n')

----------------------------------------------------------------------
Ran 728 tests in 1.184s

FAILED (failures=3, skipped=21)
pypy310: exit 1 (1.30 seconds) /tmp/pyflakes> python -m unittest discover pyflakes pid=437573
.pkg: _exit> python /usr/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  pypy310: FAIL code 1 (5.81=setup[4.50]+cmd[0.01,1.30] seconds)
  evaluation failed :( (5.86 seconds)
```

That's on 58b94a021b2d966a40a5bced06bdd6188ddb9fc2.

**Comment by asottile** [comment]
error message positions are going to be inconsistent across python versions.  for now we only test one pypy version in CI and so we're just going to keep those positions there rather than trying to make the tests work for every version of pypy
